### ISSUE TITLE
Abstract mal interprété

### ISSUE THREAD

**Issue by KumR67** [Samuel-Scalbert/SOFTware-Viz#1]
Il y a un souci d'abstract ici : http://127.0.0.1:5000/doc/hal-01949641/2P (et aussi de nom de logiciel on dirait)
idem ici :
http://127.0.0.1:5000/doc/hal-03871660/WamEnv%20API%20GUI

**Comment by Samuel-Scalbert** [comment]
fixed in : d659d9f
