### ISSUE TITLE
Problème duplicatas dans les contextes

### ISSUE THREAD

**Issue by Samuel-Scalbert** [Samuel-Scalbert/SOFTware-Viz#15]
Il y a des duplicatas dans les contexts ex: [SEP2P](http://127.0.0.1:5000/doc/hal-03404125/SEP2P)

L'erreur provient de PDF faulteux et c'est une erreur présente dans SOFTware-Sync (fixed).

Cette issue pose la question de la DB => #14

**Comment by Samuel-Scalbert** [comment]
![Capture d’écran du 2024-05-30 16-04-23](https://github.com/Samuel-Scalbert/SOFTware-Viz/assets/32683708/d3c7dd14-0825-44ff-be57-774c40159db0)
@AlainMonteil

**Comment by KumR67** [comment]
ok pour moi, il n'y a plus de duplicates

**Comment by KumR67** [comment]
Maintenu ouvert car rien fait de spécial pour que ça disparaisse.

**Comment by KumR67** [comment]
Problème toujours là: http://127.0.0.1:5000/doc/hal-02070827/Big-DAWG
![image](https://github.com/Samuel-Scalbert/SOFTware-Viz/assets/153999580/c630e3ee-5182-4cd0-80a6-779c8415f6bb)

**Comment by Samuel-Scalbert** [comment]
Oui ici aussi : http://127.0.0.1:5000/doc/hal-03514297/ALGERIA

**Comment by Samuel-Scalbert** [comment]
fixed here : 54733e89b33011c5e69d0d9f000011315a2cb4d8

(le bug provenait des duplicatas dans les JSON et une query défectueuse)

@KumR67
