### ISSUE TITLE
Erreur type de mention

### ISSUE THREAD

**Issue by KumR67** [Samuel-Scalbert/SOFTware-Viz#2]
http://127.0.0.1:5000/doc/hal-02269201/SEP2P : mention "created" devrait être "used" 
Idem pour les mentions "created d

Amber
BitsAbout
CloudLocker
CouchDB
Digi.me
Distant Viewing Toolkit
DIY
GPredictor
Helixee
MirageOS
MyCloud
OpenPDS
Oracle M
PlugDB
Pydio
SeaFile
seL4
SolveDB
SpiderOak

**Comment by Samuel-Scalbert** [comment]
J'ai l'impression que le problème est déjà régler ? @KumR67

**Comment by KumR67** [comment]
@Samuel-Scalbert , quand je clique sur le lien de SEP2P, c'est toujours "created" au lieu de "used".

**Comment by Samuel-Scalbert** [comment]
fixed in : b546c90eb2b89f6dded0db44241f9a3b9c933ea4
