### ISSUE TITLE
Mention comprenant un tiret de fin de ligne

### ISSUE THREAD

**Issue by KumR67** [Samuel-Scalbert/SOFTware-Viz#23]
Dans le PDF :
![image](https://github.com/Samuel-Scalbert/SOFTware-Viz/assets/153999580/8535d10b-e1ae-46ef-9fd3-e864a749696d)

Résultat dans SOFT-Viz
![image](https://github.com/Samuel-Scalbert/SOFTware-Viz/assets/153999580/df09b74d-9148-4d4f-a673-888dc315da1e)

**Comment by Samuel-Scalbert** [comment]
Tu veux dire le logiciel est ESTOCADA et non ES-TOCADA ?

**Comment by KumR67** [comment]
oui

**Comment by KumR67** [comment]
http://127.0.0.1:5000/doc/hal-02070827/ES-TOCADA

**Comment by Samuel-Scalbert** [comment]
J'ai mis en place une solution : je vérifie toutes les occurrences d'un logiciel dans un document, puis je compte le nombre d'occurrences pour chaque nom de logiciel. Si je trouve un logiciel qui apparaît avec un "-", je vérifie s'il existe une version sans "-" et, si c'est le cas, je remplace la version avec "-" par celle sans "-" si elle a moins d'occurrences.

Cette approche est nécessaire tant que nous n'avons pas de noms d'autorité pour chaque logiciel.

(il faut reset la db)

Le lien que tu as fourni ne fonctionne plus, et les mentions sont maintenant disponibles à cette adresse :

http://127.0.0.1:5000/doc/hal-02070827/ESTOCADA
