### ISSUE TITLE
Logiciel non repéré

### ISSUE THREAD

**Issue by KumR67** [Samuel-Scalbert/SOFTware-Viz#3]
http://127.0.0.1:5000/doc/hal-02269201/SEP2P :  DISPERS n'a pas été repéré comme logiciel

**Comment by Samuel-Scalbert** [comment]
DISPERS n'est pas dans la db pour ce doc, comment tu sais qu'il est dans ce document ? Il n'est pas dans software non plus ...

**Comment by Samuel-Scalbert** [comment]
Alors le software est bien dans le doc, mais non repéré ._.
