### ISSUE TITLE
Graphic in dashboard

### ISSUE THREAD

**Issue by AlainMonteil** [Samuel-Scalbert/SOFTware-Viz#33]
hi on the dashboard : http://prod-datadcis-app.inria.fr:8040/dashboard
it seems that there is error around count and graphics ! 
For cheese graphics on mouse over 4082 for crated 
For line graphics : 256 created 
There somewhere a bug and i think there is an inversion 
Alain

**Comment by Samuel-Scalbert** [comment]
Ah oui ! J'ai en effet inversé les datas…

**Comment by Samuel-Scalbert** [comment]
fixed here : 18fcd2886a2df0dbef2ff33b296c58edb47d857e
